### ISSUE TITLE
Syntax problem in gcode Marlin

### ISSUE THREAD

**Issue by silvanopas** [LightBurnSoftware/Documentation#29]
Hello
When I use the Z axis with Marlin, the gcode is not written correctly.
He writes G0Z27 instead of C0 Z27 omitting the space
Can you solve this?
I'm evaluating the purchase of Lightburn
Thank you

**Comment by LightBurnSoftware** [comment]
Standard GCode does not require spaces - does Marlin? It's easily fixed, just bizarre that Marlin is consistently the only firmware that requires so much hand-holding.  Yes, this can be fixed.

Also, this isn't a documentation bug, so it's odd that you've chosen to report it here instead of sending via email or through our support channel, Facebook or G+ groups, etc.
