### ISSUE TITLE
MAC Built in USB Hub not Showing in Device Panel

### ISSUE THREAD

**Issue by thomas-williams** [LightBurnSoftware/Documentation#31]
I am using LightBurn on both a Mac and a PC with the same laser, and had it working on the Mac at first and was super pleased with the application. I then installed it on my PC laptop so I could prep files on the go and then simply plug the laser into my laptop to cut them. This also worked great and I like LightBurn way more than the proprietary software the laser came with. At some point I went to use the laser with the Mac and that is when this problem started. I am not sure if that is coincidence or not, but it might be worth noting. I have since been completely unable to get the laser working with LightBurn on the Mac. Still works great on the PC, but the Mac seems to have problems. Under the USB interface drop down menu I now only see the Bluetooth device and not the built in USB hub. We used to run the proprietary software through a virtual box so I went and double checked that the device was no longer being passed through to the VM, which was an issue I encountered when initially setting up LightBurn, but that was all disabled. I then went and made sure that the laser USB device was registering at all with MacOS and through both terminal and the system information panel I confirmed that MacOS saw when the laser USB controller was plugged in. This leads me to believe it is an issue with LightBurn. I have reinstalled multiple times, and even installed in fresh user accounts to make sure, nowhere does it work. If there are any log files you might need just let me know where to find them and I will attack them right away.

**Comment by LightBurnSoftware** [comment]
You've mentioned nowhere what kind of laser you have, so I'm guessing here, but since you've said "proprietary software" I'll assume it's a Ruida controller, which means an FTDI device, which are known for port locking on the Mac.  If you actually restart the Mac instead of sleep / wake, it'll clear the port lock. There are ways to fix it: https://superuser.com/questions/1135730/how-to-release-reset-serial-port-ftdi-devices-mac-osx

In the future, please note that this site is for our documentation, not support.  Contact the support email listed on our webpage, use the Facebook group, or Google Plus group.
