### ISSUE TITLE
Feature - Crop imported image

### ISSUE THREAD

**Issue by leitenky** [LightBurnSoftware/Documentation#36]
Just wondering if it's possible to add a crop feature to imported images or even traced images.  Being able to import a bmp/jpg and crop it In lightburn would be very handy

**Comment by LightBurnSoftware** [comment]
You are leaving these comments on our documentation github. We have an entire forum for discussions, and a feature request site, both of which are listed on the “Contact us” page of our site.  I will move these there, and we’ll be closing commenting on the docs site because this makes it harder for us to track requests.

**Comment by LightBurnSoftware** [comment]
https://lightburn.fider.io/posts/374/to-crop-images
